dist: trusty
sudo: true

language: node_js
node_js:
  - '10'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
before_install:
  cd CFC/ClientApp

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build